name: Version Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install semver
      
      - name: Check PR branch versions match
        id: pr_version
        run: |
          PR_VERSION=$(node scripts/version-check.js)
          echo "version=$PR_VERSION" >> $GITHUB_OUTPUT
      
      - name: Get target branch version
        id: target_version
        run: |
          git checkout origin/${{ github.base_ref }}
          TARGET_VERSION=$(node -p "require('./package.json').version")
          echo "version=$TARGET_VERSION" >> $GITHUB_OUTPUT
          
          # Return to PR branch and check version comparison
          git checkout -
          node scripts/version-check.js "$TARGET_VERSION"
